name: Deploy site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --force
        working-directory: ./client

      - name: Build project
        # Vite에게 설정 파일 위치와 index.html 위치를 직접 알려줍니다.
        run: |
          cd client
          CI=false npx vite build --base=/internet-landing/ ./index.html
        
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 빌드 완료 후 생성되는 폴더 경로
          path: './client/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
